### ISSUE TITLE
Does this project use protobuf?

### ISSUE THREAD

**Issue by ianklatzco** [trailofbits/grr#7]
It doesn't look like there's any protobuf code anywhere, but there's two instances where it's referenced in the Makefile: 

https://github.com/trailofbits/grr/blob/master/Makefile#L65

https://github.com/trailofbits/grr/blob/master/Makefile#L108

Removing those doesn't seem to cause any problems at compile or runtime.

**Comment by pgoodman** [comment]
Not anymore. It used it.
